name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name:  Build and Push Images
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
      RELEASE_VERSION: ~
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        run: |
          docker run --rm -e GITHUB_TOKEN=${GITHUB_TOKEN} -v "${PWD}":/app michcald/semantic-release
          if test -f .RELEASE_VERSION; then
            release_version="$(cat .RELEASE_VERSION)"
            echo "::set-env name=RELEASE_VERSION::$release_version"
          fi
      - name: Build and Push
        if: env.RELEASE_VERSION != ''
        run: make
